# Database Connection Properties for Sunrise Dental Clinic System (Cloud TiDB)
db.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/sunrise_dental_db?sslMode=VERIFY_IDENTITY&useSSL=true&serverTimezone=UTC
db.user=42UVtMmfzWtuANk.root
db.password=xn0oZNxqPx9YNeU3
